[package]
name = "ffs-ext4"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ffs-ondisk = { workspace = true }

[lints]
workspace = true
