[package]
name = "ffs"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ffs-core = { workspace = true }

[lints]
workspace = true
